name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Labo0

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        working-directory: src
        run: | 
          python -m pytest 

      - name: Déploiement avec SSH
        if: success()
        run: |
          # Installer sshpass pour l'authentification par mot de passe
          sudo apt-get update && sudo apt-get install -y sshpass
          
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER_HOST }} "cd log430-a25-labo0 && git pull origin main && sudo docker build -t labo0-calculator . && sudo docker compose up -d"

